import type { Metadata } from "next";
import { Bellefair } from "next/font/google";
import { Barlow } from "next/font/google";
import { Barlow_Condensed } from "next/font/google";
import { Header } from "./components/Header/Header";
import styles from "./styles/global.module.scss";
import './styles/global.scss';

const bellefair = Bellefair({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap'
});

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  display: 'swap'
});

const barlowCondensed = Barlow_Condensed({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Interplanetary tourism",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${barlow.className} ${barlowCondensed.className} ${bellefair.className}`}>
      <body className={styles.body}>
        <Header/>
        <main>{children}</main>
      </body>
    </html>
  );
}
